### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by IIIIIIIIIIIIIIIIIIIIIIIIIIIIIll** [IRIS-Team/IRIS#1]
I keep getting “‘bool’ object is not subscriptable” I don’t know to much about coding, i’m not sure if that means there is something wrong with my format of the search or something to do with something else. If someone could try to help out i’d appreciate it ( This only happens on, Email Breach and IP Breach )

**Comment by rpie** [comment]
The ‘bool’ object is not subscriptable is an error stating that there was no results returned, but I'll add a except statement for easier output thank you for pointing this out :L
