### ISSUE TITLE
Help Im gonna get hacked by hellsec

### ISSUE THREAD

**Issue by ItzRover** [IRIS-Team/IRIS#11]
So randomly today hellsec pulled some random gibbrish out of his upper anus named a "RA Code" because I tried to QR Code grab him. Now I am shaking and crying as I am unaware what this does. This may be the last time I speak on this github or in general. Wish me luck

**Comment by sql69** [comment]
![](https://c.tenor.com/aoA-UYEw4wYAAAAC/take-the-l-loser.gif)

**Comment by rpie** [comment]
spam
