### ISSUE TITLE
Zalgo.

### ISSUE THREAD

**Issue by KASLR** [IRIS-Team/IRIS#9]
*Clears throat*, hey retard didn't I say you can't code and then proceeded to say "why do I have dev role then", and hellsec even said you contributed nothing to this project, and just gets targets? LMFAO? You have done nothing you broke skid, pov: braindead retard who can't code

**Comment by FarmerJoe1337** [comment]
I see you're struggling to fix your issues just delete system32 and your issues should be fixed :)

**Comment by psauxx** [comment]
> _Clears throat_, hey retard didn't I say you can't code and then proceeded to say "why do I have dev role then", and hellsec even said you contributed nothing to this project, and just gets targets? LMFAO? You have done nothing you broke skid, pov: braindead retard who can't code

Ngl i agree all zalgo can do i make fun of others who accomplish more then him. He doesn't code at all hes not even a dev i consider him as a little kid playing to much hvh

**Comment by rpie** [comment]
spam
